Properties:
  domain: cds.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    study: studies
    study_admin: study_admins
    participant: participants
    diagnosis: diagnoses
    treatment: treatments
    specimen: specimens
    sample: samples
    file: files
    genomic_info: genomic_info


  type_mapping:
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    list: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    study: phs_accession
    participant: study_participant_id
    diagnosis: study_diagnosis_id
    treatment: treatment_id
    specimen: specimen_id
    sample: sample_id
    file: file_id
    genomic_info: genomic_info_id
    program: program_acronym
    image: study_link_id
